---
title: "PE2"
author: "Joe Mienko"
date: "4/13/2018"
output: pdf_document
---

## Practical Exercise 2

Recall the following details from our Week 1 Practical Exercise: 

**In Scenario 1**

> Julia has a 3 and 4 year old child who have been placed in foster care. She has become extremely depressed since this took place. While she is still taking part in weekly parent-child visitation sessions, her depressive symptoms have been making it difficult for her to engage with her children or manage their behavior in visitation sessions. The court has ordered you to provide Julia with "parenting services". 

**In Scenario 2**

> Jim is the non-custodial legal father of Jonathan, a 16yo male who has been recently placed in foster care due to a variety of behavioral and criminal problems at school and in the community. Jonathan's mother has stopped participating in the dependency process, but Jim has remained actively engaged and is willing to be a permanent placement resource for Jonathan. Prior to placement with Jim, the court is concerned that Jonathan's behavioral problems (including anger management problems) will be difficult to manage for Jim. The court has ordered you to find "therapeutic services to support the relationship between Jim and Jon".

## Getting Data

**In Scenario 1**

One of the sources of data identified for collection in scenario 1 was items from a survey used by the Communities that Care (CTC) program. For this exercise, we will focus specifically on the Favorable Attitudes Toward Antisocial Behavior subscale. Which includes 5 items rated on a Likert scale ranging from 1 to 4. Data for this scenario can be generated by running the provided `fatab_sim(seed = 123456)` function in R. 

**In Scenario 2**

One of the sources of data identified for collection in scenario 2 was the Acceptance and Action Questionnaire (AAQ). The version of the AAQ used in this exercise has 9 items rated on a Likert scale raning from 1 to 7. Data for this scenario can be generated by running the provided `aaq_sim(seed = 123456)` function in R. 

Each function has a single parameter for a random seed which should be set to your student number. This will ensure that each student has a slightly different set of data for this exercise.

## Your tasks for this practical exercise are as follows: 

1. Choose a scenario to work on, 

2. Generate data from the function associated with your scenario using the provided function, 

3. Make a graph of these data as decribed in class, 

4. Calculate an overall average of the data as described in class, 

5. Calculate an overall average of the data as described in class, and 

6. Calculate an overall standard deviation of the data as described in class.




